name: Sync Submodule

on:
  repository_dispatch:
    types: [ update-submodule ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Update Submodule
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git submodule update --remote --merge
        git add .
        git commit -m "chore: update blog submodule to latest" || exit 0
        git push
