name: Update Portfolio Submodule

on:
  push:
    branches:
    - main # 或者是你的博客主分支

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Remote Dispatch
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/roshad/portfolio/dispatches \
          --fail \
          -d '{"event_type": "update-submodule"}'
